name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Xcode
      # You may pin to the exact commit or the version.
      # uses: sinoru/actions-setup-xcode@c1ccec544dad194d713c8a5288f0d90eff82721c
      uses: sinoru/actions-setup-xcode@v1.1.2
      with:
        xcode-version: '12.4'
        apple-id: ${{ secrets.APPLE_ID }}
        apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Upload built files
      uses: actions/upload-artifact@v2
      with:
        name: compiled
        path: .build
